### ISSUE TITLE
Can the type-system (or custom monads) help in cache-invalidation?

### ISSUE THREAD

**Issue by saurabhnanda** [vacationlabs/haskell-webapps#12]

**Comment by sudhirvkumar** [comment]
@saurabhnanda 

which cache? Redis? or HTTP?

**Comment by saurabhnanda** [comment]
Redis

**Comment by sudhirvkumar** [comment]
@saurabhnanda 

I am not sure how we will be able to combine an external service with Haskell type system.
The only thing I can think is to handle it manually. When things change put that to a common queue and have a worker do the magic of Cache Invalidation.

I am very curious to see if Haskell can do anything more in this regard. So I will be watching this space closely

**Comment by saurabhnanda** [comment]
Discussion moved to #15
