### ISSUE TITLE
Authorization strategies

### ISSUE THREAD

**Issue by jfoutz** [vacationlabs/haskell-webapps#16]
Per function access to a service is risky. Lack of access can be frustrating for users, but is ultimately fairly easy to resolve, just grant access to that role. The other case, permissions being open is much more dangerous. Sensitive information could be leaked.

I have two broad suggestions for limiting that risk. 

1, Completely separate all user facing services from tenant facing services. All of the user facing stuff should be open by default. All tenant facing stuff should be closed by default. A user might need to be logged in to complete the sale, but other than that, they should be able to see everything.

2, Centralize  users, roles and permissions in postgres tables for the tenant facing api. There's no way to automatically determine what permissions are correct for a given role, but if you put them all in one place, at least you can look at what roles can do, and add that to your code review process. Build a nice UI for it.

I might have misunderstood the specific issues you were having, but they sure sounded like process problems, rather than something technical that was getting in the way. If a developer forgets to open up a "sensitive" part of the API, it just won't work. which is fine. You can help people remember at code review time. Or even make it part of the ticket when a feature or bug is opened against the private API.

**Comment by saurabhnanda** [comment]
@jfoutz merge this with #9, which was opened to discuss this issue?
