### ISSUE TITLE
HDBC+Servant: Initial sprint

### ISSUE THREAD

**Issue by jfoutz** [vacationlabs/haskell-webapps#33]
### Stack

HDBC (close to raw SQL) + Servant
### Domain API

Take basic types for each query, execute the query, return simple rows for results. It is the responsibility of the JSON api to convert to and from haskell objects, for tenant, user, role, permission. 

At the end of this sprint DomainApi should export correct versions of
- createTenant, getTenant, activateTenant
- createUser, activateUser, deactivateUser, getUser
- createRole, getRole,
- createPermission, 
- assignRole removeRole (taking userID and roleID)
- assignPermission, removePermission (taking permissionID and roleID)
- getPermissions (taking roleid)
- getPermissions (taking userid)

**Time estimate:** 10 hours
### Tenant JSON API

Connect tenant domain methods to the tenant JSON API, and resolve any specific issues. 
### HDBC Errors

HDBC queries may have database specific errors. for example the database is not reachable, authentication fails, or a query violates a database constraint.

I don't know what the consequences are for a failed query. Need to test the error condition to ensure the process does not crash. Consider, but do not implement reporting options - perhaps logging, perhaps health checks, perhaps both. this needs discussion.

**Time estimate:** 4 hours - need to test a few cases, database down, schema change. Just ensure no crash and a reasonable http return code is sent.
### Connection pools

Investigate this library, https://hackage.haskell.org/package/resource-pool and if it's acceptable, implement resource pools for connection objects. If this library won't work, connection pooling will move to the next sprint.

**Time estimate:** 6 hours. The library looks straightforward, it should be a matter of changing the Config object to take a resource-pool, and correctly allocate/deallocate connections.
### Figure out monad for DB actions

HDBC queries run in IO. currently the code requires lift.lift to pull the execution up through the EitherT and the ReaderT. 

Use this example http://stackoverflow.com/a/31300720 To convert the AppM type to a newtype, and automatically derive the MonadReader implementation. 

**Time estimate:** 8 hours. There is a working example, but there are a lot of funny little details to investigate

**Comment by saurabhnanda** [comment]
Thanks. Perfect balance of scope and detail!

Are you focusing only on the domain API or the full stack, ie servant
handlers calling these domain APIs ?

**Comment by jfoutz** [comment]
I'm going to complete Tenant for the whole stack - but not for any of the other methods.

I wound up needing a Domain api because of monad mismatch. For now, i'm just going to`lift.lift Domain.getTenant id` The third design goal will get rid of that `lift.lift`
