### ISSUE TITLE
Spock+Opaleye - Initial sprint

### ISSUE THREAD

**Issue by sras** [vacationlabs/haskell-webapps#36]
## Building a shopping cart web app using Spock web framework and Opaleye
1. Create database schema,  Install and configure Opaleye and define schema for the same -- 5 hr
2. See if it is better to have a flat structure for the data model, Or if Opaleye powerful enough to accept a nested structure for models, but specify the relations to be loaded in a specific query? --8 hr
3. Write CRUD functions with validation, for entities that also takes care of handling the housekeeping columns 

Initial api will include data structures representing Users, Roles and Tenants

Api function will include CreateRole, DeleteRole, CreateUser, UpdateUser, ActivateUser, AssignRole, RemoveRole, DeactivateUser, CreateTenant, UpdateTenant, ActivateTenant, and DeactivateTenant -- 8 hrs

**Comment by saurabhnanda** [comment]
Great - let's get started!

**Comment by sras** [comment]
# Closing the sprint

## Things accomplished.
1. Implemented the domain api functions.
2. Figured out how to work with Opaleye database lib. Thanks to @saurabhnanda  for all the help.
3. Implemented a json endpoint using Spock framework.

## Things that were pushed to the next sprint
1. Deal with housekeeping columns.
2. Evaluate and Integrate a validation library.

Things learned from this sprint have been added to the [tips.txt](https://github.com/vacationlabs/haskell-webapps/blob/master/SpockOpaleye/tips.txt) file
